INSERT INTO it_3_7.entity_with_sasi_indices(id, clust, prefixnontokenizer, containsstandardanalyzer, numeric, sparse)
VALUES(${id}, 1, 'speed runner', 'forever love', 11, 11);

INSERT INTO it_3_7.entity_with_sasi_indices(id, clust, prefixnontokenizer, containsstandardanalyzer, numeric, sparse)
VALUES(${id}, 2, 'long run', 'lovers', 12, 12);

INSERT INTO it_3_7.entity_with_sasi_indices(id, clust, prefixnontokenizer, containsstandardanalyzer, numeric, sparse)
VALUES(${id}, 3, 'running man', 'the white gloves', 13, 13);

INSERT INTO it_3_7.entity_with_sasi_indices(id, clust, prefixnontokenizer, containsstandardanalyzer, numeric, sparse)
VALUES(${id}, 4, 'speedster', 'the loving man', 14, 14);

INSERT INTO it_3_7.entity_with_sasi_indices(id, clust, prefixnontokenizer, containsstandardanalyzer, numeric, sparse)
VALUES(${id}, 5, 'long grain', 'no love', 15, 15);

INSERT INTO it_3_7.entity_with_sasi_indices(id, clust, prefixnontokenizer, containsstandardanalyzer, numeric, sparse)
VALUES(${id}, 6, 'long grain', 'the chair is dancing', 16, 16);