INSERT INTO achilles_embedded.entity_with_clusterings(id, uuid, date, value)
VALUES(${id1}, ${uuid1}, ${date1}, 'val1');

INSERT INTO achilles_embedded.entity_with_clusterings(id, uuid, date, value)
VALUES(${id2}, ${uuid2}, ${date2}, 'val2');

INSERT INTO achilles_embedded.entity_with_clusterings(id, uuid, date, value)
VALUES(${id3}, ${uuid3}, ${date3}, 'val3');

INSERT INTO achilles_embedded.entity_with_clusterings(id, uuid, date, value)
VALUES(${id4}, ${uuid4}, ${date4}, 'val4');

INSERT INTO achilles_embedded.entity_with_clusterings(id, uuid, date, value)
VALUES(${id5}, ${uuid5}, ${date5}, 'val5');
