INSERT INTO it_3_8.entity_for_aggregate(partition, clustering, doubleval, stringVal) VALUES (${id}, 1, 1.0, '1.0');
INSERT INTO it_3_8.entity_for_aggregate(partition, clustering, doubleval, stringVal) VALUES (${id}, 2, 2.0, '2.0');
INSERT INTO it_3_8.entity_for_aggregate(partition, clustering, doubleval, stringVal) VALUES (${id}, 3, 3.0, '3.0');
INSERT INTO it_3_8.entity_for_aggregate(partition, clustering, doubleval, stringVal) VALUES (${id}, 4, 4.0, '4.0');
INSERT INTO it_3_8.entity_for_aggregate(partition, clustering, doubleval, stringVal) VALUES (${id}, 5, 5.0, '5.0');