INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id1}, 1);
INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id1}, 2);
INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id1}, 3);

INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id2}, 1);
INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id2}, 2);
INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id2}, 3);

INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id3}, 1);
INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id3}, 2);
INSERT INTO it_3_6.entity_with_clustering(id, clust) VALUES(${id3}, 3);