INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(1, 1, 'val11');
INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(1, 2, 'val12');
INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(1, 3, 'val13');
INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(2, 1, 'val21');
INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(2, 2, 'val22');
INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(3, 1, 'val31');
INSERT INTO achilles_embedded.index_on_clustering(partition, clustering, value) VALUES(3, 2, 'val32');